title: Lydia Nicolau
logo: docs/assets/LydiaNicolauProfessionalPhoto.jpg
description: Computer Science | Public & Professional Writing | Communication Studies
#show_downloads: true
theme: jekyll-theme-minimal
